# Generated by Django 3.1.1 on 2020-10-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photose',
            name='choices',
            field=models.CharField(blank=True, choices=[('1st', '1'), ('2nd', '2'), ('3rd', '3')], max_length=30, null=True),
        ),
    ]
