# Generated by Django 3.1.1 on 2020-10-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runo', '0003_auto_20201018_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(max_length=30, upload_to='photos')),
                ('desc', models.CharField(max_length=30)),
                ('choices', models.CharField(blank=True, choices=[('1st', '1'), ('2nd', '2'), ('3rd', '3'), ('4th', '4'), ('5th', '5'), ('6th', '6')], max_length=30, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Photose',
        ),
    ]
