# Generated by Django 3.1.1 on 2020-10-18 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runo', '0004_auto_20201018_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photos',
            old_name='choices',
            new_name='position',
        ),
    ]
