# Generated by Django 3.1.1 on 2020-10-19 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runo', '0005_auto_20201018_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelcImgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcImg', models.ImageField(max_length=30, upload_to='welcome')),
                ('extraImg1', models.ImageField(max_length=30, upload_to='welcome')),
                ('extraImg2', models.ImageField(max_length=30, upload_to='welcome')),
            ],
        ),
        migrations.AlterField(
            model_name='photos',
            name='position',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='Welc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='runo.welcimgs')),
            ],
        ),
    ]
