# Generated by Django 3.1.1 on 2020-10-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runo', '0006_auto_20201019_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelcLeaders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcImg', models.ImageField(max_length=30, upload_to='welcome')),
                ('extraImg1', models.ImageField(max_length=30, upload_to='welcome')),
                ('extraImg2', models.ImageField(max_length=30, upload_to='welcome')),
            ],
        ),
        migrations.DeleteModel(
            name='Welc',
        ),
    ]
