# Generated by Django 3.1.1 on 2020-10-20 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runo', '0007_auto_20201019_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='welcleaders',
            old_name='extraImg1',
            new_name='extraLeader1',
        ),
        migrations.RenameField(
            model_name='welcleaders',
            old_name='extraImg2',
            new_name='extraLeader2',
        ),
        migrations.RenameField(
            model_name='welcleaders',
            old_name='welcImg',
            new_name='welcLeader',
        ),
    ]
