# Generated by Django 3.1.1 on 2020-10-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runo', '0008_auto_20201020_0530'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsImg', models.ImageField(max_length=30, upload_to='photos')),
                ('desc', models.CharField(max_length=30)),
                ('position', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=30, null=True)),
            ],
        ),
    ]
