# Generated by Django 3.1.1 on 2020-10-21 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runo', '0009_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='desc',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='photos',
            name='desc',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='welcimgs',
            name='extraImg1',
            field=models.ImageField(blank=True, max_length=30, null=True, upload_to='welcome'),
        ),
        migrations.AlterField(
            model_name='welcimgs',
            name='extraImg2',
            field=models.ImageField(blank=True, max_length=30, null=True, upload_to='welcome'),
        ),
        migrations.CreateModel(
            name='Welcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writeHead1', models.CharField(blank=True, max_length=100, null=True)),
                ('write1', models.TextField(blank=True, null=True)),
                ('resources', models.CharField(max_length=150)),
                ('contact1', models.CharField(blank=True, max_length=100, null=True)),
                ('contact2', models.CharField(blank=True, max_length=100, null=True)),
                ('file1', models.FileField(blank=True, max_length=30, null=True, upload_to='welcFiles')),
                ('file2', models.FileField(blank=True, max_length=30, null=True, upload_to='welcFiles')),
                ('img1', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='welcHome', to='runo.welcimgs')),
            ],
        ),
    ]
