# Generated by Django 3.1.1 on 2020-10-21 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runo', '0010_auto_20201021_0716'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Welcome',
            new_name='Welcometab',
        ),
    ]
