# Generated by Django 3.1.1 on 2020-10-21 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runo', '0011_auto_20201021_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='welcometab',
            name='email1',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='welcometab',
            name='email2',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='welcometab',
            name='img2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='welcHome2', to='runo.welcimgs'),
        ),
        migrations.AddField(
            model_name='welcometab',
            name='write2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='welcometab',
            name='writeHead2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='welcometab',
            name='resources',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
