# Generated by Django 3.1.1 on 2020-10-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runo', '0013_auto_20201022_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='welcometab4',
            name='displayName1',
            field=models.CharField(default='Resource1', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='welcometab4',
            name='displayName2',
            field=models.CharField(default='Resource1', max_length=50),
            preserve_default=False,
        ),
    ]
