# Generated by Django 3.1.1 on 2020-10-22 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runo', '0015_auto_20201022_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='welcometab',
            name='img1L',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='welcLead', to='runo.welcleaders'),
        ),
        migrations.AddField(
            model_name='welcometab2',
            name='img2L',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='welcLead2', to='runo.welcleaders'),
        ),
    ]
