# Generated by Django 3.1.1 on 2020-10-23 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runo', '0016_auto_20201022_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='newsDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsBody', models.TextField()),
                ('newsHead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='newsTitle', to='runo.news')),
                ('newsImg', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='newsText', to='runo.news')),
            ],
        ),
    ]
