# Generated by Django 3.1.1 on 2020-10-23 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runo', '0017_newsdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdetail',
            name='newsHead',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newsTitle', to='runo.news'),
        ),
        migrations.AlterField(
            model_name='newsdetail',
            name='newsImg',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newsText', to='runo.news'),
        ),
    ]
