# Generated by Django 3.1.1 on 2020-10-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runo', '0019_auto_20201023_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(max_length=50, upload_to='about')),
                ('title', models.CharField(max_length=40)),
                ('body', models.TextField()),
            ],
        ),
    ]
