# Generated by Django 3.1.1 on 2020-10-24 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runo', '0021_about2_about3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about2',
            old_name='body',
            new_name='body2',
        ),
        migrations.RenameField(
            model_name='about2',
            old_name='img',
            new_name='img2',
        ),
        migrations.RenameField(
            model_name='about2',
            old_name='title',
            new_name='title2',
        ),
        migrations.RenameField(
            model_name='about3',
            old_name='body',
            new_name='body3',
        ),
        migrations.RenameField(
            model_name='about3',
            old_name='img',
            new_name='img3',
        ),
        migrations.RenameField(
            model_name='about3',
            old_name='title',
            new_name='title3',
        ),
    ]
