# Generated by Django 3.1.1 on 2020-10-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runo', '0022_auto_20201024_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('position', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=30, null=True)),
            ],
        ),
    ]
