# Generated by Django 3.1.1 on 2020-10-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runo', '0024_auto_20201025_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='admitfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file1', models.FileField(blank=True, null=True, upload_to='admission_files')),
                ('name1', models.CharField(max_length=60)),
                ('file2', models.FileField(blank=True, null=True, upload_to='admission_files')),
                ('name2', models.CharField(max_length=60)),
                ('file3', models.FileField(blank=True, null=True, upload_to='admission_files')),
                ('name3', models.CharField(max_length=60)),
            ],
        ),
    ]
