# Generated by Django 3.1.1 on 2020-11-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runo', '0027_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footerabout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_about', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Footerdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200)),
                ('school_address', models.CharField(max_length=500)),
                ('school_motto', models.CharField(max_length=500)),
            ],
        ),
    ]
