# Generated by Django 3.1.1 on 2020-11-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runo', '0029_auto_20201109_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footercontact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_phone', models.CharField(default='12345', max_length=15)),
                ('school_mail', models.EmailField(default='schoolmail', max_length=60)),
            ],
        ),
    ]
